server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    date-format: yyyy-MM-dd
    static-path-pattern: /static/**
  datasource:
#    name: java
    url: jdbc:mysql://localhost:3306/shoppingweb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
## 该配置节点为独立的节点
mybatis:
#  扫描所有的dao层的xml
  mapper-locations: classpath:com/cheer/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

